riding_sport_clubs/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('riding_sport_clubs.web_clubs.urls')),
    path('account/', include('riding_sport_clubs.web_accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)\
              + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'riding_sport_clubs.views.page_not_found_view'

riding_sport_clubs/web_clubs/models.py
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator, MinValueValidator
from django.db import models
from django.urls import reverse

from riding_sport_clubs.base_validators.validators import owner_name_validator, name_validator, phone_number_validator


class Club(models.Model):
    CLUB_NAME_MIN_LENGTH = 2
    CLUB_NAME_MAX_LENGTH = 50
    OWNER_NAME_MIN_LENGTH = 2
    OWNER_NAME_MAX_LENGTH = 35
    CLUB_NUMBER_MAX_LENGTH = 16
    CLUB_NUMBER_MIN_LENGTH = 8
    UPLOAD_CLUB_LOGO = 'clubs_logo'

    club_name = models.CharField(
        max_length=CLUB_NAME_MAX_LENGTH,
        validators=(
            MinLengthValidator(CLUB_NAME_MIN_LENGTH),
        ),
        unique=True,
    )

    owner = models.CharField(
        max_length=OWNER_NAME_MAX_LENGTH,
        validators=(
            MinLengthValidator(OWNER_NAME_MIN_LENGTH),
            owner_name_validator,
        ),
    )

    email_club = models.EmailField()

    club_phone_number = models.CharField(
        max_length=CLUB_NUMBER_MAX_LENGTH,
        validators=(
            MinLengthValidator(CLUB_NUMBER_MIN_LENGTH),
            phone_number_validator,
        ),
        null=True,
        blank=True,
    )

    award_gold = models.IntegerField(
        default=0,
    )

    award_silver = models.IntegerField(
        default=0,
    )

    award_bronze = models.IntegerField(
        default=0,
    )

    rating = models.IntegerField(
        default=0,
    )

    address = models.TextField(
        null=True,
        blank=True,
    )

    description = models.TextField(
        null=True,
        blank=True,
    )

    club_logo = models.ImageField(
        upload_to=UPLOAD_CLUB_LOGO,
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.club_name

    def get_absolute_url(self):
        return reverse('club info', kwargs={'pk': self.pk})


class Trainer(models.Model):
    TRAINER_FIRST_NAME_MAX_LENGTH = 25
    TRAINER_LAST_NAME_MAX_LENGTH = 25
    AGE_MIN_VALUE = 1
    TRAINER_NUMBER_MAX_LENGTH = 16
    TRAINER_NUMBER_MIN_LENGTH = 8
    UPLOAD_TRAINER_PHOTO = 'trainer_photos'

    trainer_first_name = models.CharField(
        max_length=TRAINER_FIRST_NAME_MAX_LENGTH,
        validators=(
            name_validator,
        ),
    )

    trainer_last_name = models.CharField(
        max_length=TRAINER_LAST_NAME_MAX_LENGTH,
        validators=(
            name_validator,
        ),
    )

    trainer_age = models.IntegerField(
        validators=(
            MinValueValidator(AGE_MIN_VALUE),
        ),
    )

    trainer_phone_number = models.CharField(
        max_length=TRAINER_NUMBER_MAX_LENGTH,
        validators=(
            MinLengthValidator(TRAINER_NUMBER_MIN_LENGTH),
            phone_number_validator,
        ),
        null=True,
        blank=True,
    )

    trainer_photo = models.ImageField(
        upload_to=UPLOAD_TRAINER_PHOTO,
        null=True,
        blank=True,
    )

    trainer_info = models.TextField(
        null=True,
        blank=True,
    )

    clubs = models.ForeignKey(
        Club,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return f"{self.trainer_first_name}  {self.trainer_last_name}"


class HorseBreed(models.Model):
    BREED_MAX_LENGTH = 35
    COLOR_MAX_LENGTH = 40
    USES_MAX_LENGTH = 40
    DESCRIPTION_MAX_LENGTH = 400000
    BREED_UPLOAD_PHOTO = 'breeds_photo'

    breed = models.CharField(
        max_length=BREED_MAX_LENGTH,
    )

    average_height = models.IntegerField()

    horse_color = models.CharField(
        max_length=COLOR_MAX_LENGTH,
    )

    common_uses = models.CharField(
        max_length=USES_MAX_LENGTH,
    )

    breed_description = models.TextField(
        max_length=DESCRIPTION_MAX_LENGTH,
    )

    breed_photo = models.ImageField(
        upload_to=BREED_UPLOAD_PHOTO,
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.breed

templates/web/breed_info.html
{% extends 'bases/base.html' %}
{% load static %}

{% block co_base %}
    <div id="breed-info" class="back-ground-club-info">
        <div class="main-div-breed">
        <!-- only for demo -->
            {% if object.breed == 'East Bulgarian' %}
            <img src="{% static "images/breeds_pictures/base-East-BG.jpg" %}" alt="Breed Picture">
            {% elif object.breed == 'Friesian' %}
            <img src="{% static "images/breeds_pictures/base-friesian.jpg" %}" alt="Breed Picture">
            {% elif object.breed == 'Thoroughbred' %}
            <img src="{% static "images/breeds_pictures/base-Thoroughbred-white-color.png" %}" alt="Breed Picture">
            {% elif object.breed == 'Arab' %}
            <img src="{% static "images/breeds_pictures/6-Different-Types-Of-Arabian-Horses.jpg" %}" alt="Breed Picture">
            {% endif %}
        <!-- -->
            <p><strong>Breed:</strong>&nbsp;&nbsp;{{ object.breed }}</p>
            <p><strong>Average Height:</strong>&nbsp;&nbsp;{{ object.average_height }}&nbsp;cm.</p>
            <p><strong>Color:</strong>&nbsp;&nbsp;{{ object.horse_color }}</p>
            <p><strong>Uses:</strong>&nbsp;&nbsp;{{ object.common_uses }}</p>
            <p><strong>Story:</strong>&nbsp;&nbsp;{{ object.breed_description }}</p>
        </div>
    </div>
{% endblock %}

templates/web/club_edit.html
{% extends 'bases/base.html' %}
{% load static %}

{% block co_edit_club %}
    <div id="edit-club" class="club-edit-content">
        <fieldset>
            <legend class="cl-ed">Edit Club</legend>
            <a href="/" ><i class="fa-solid fa-xmark fa-club"></i></a>
            <form class="cl-ed-form" method="post" action="{% url 'edit club' object.pk %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="cl-ed-option">
                    <a href="#" class="edit-a">Edit Trainers</a>
                    <button class="edit-btn">Edit</button>
                </div>
            </form>
        </fieldset>
    </div>

{% endblock %}

templates/web/club_info.html
{% extends 'bases/base.html' %}
{% load static %}


{% block co_base %}
     <section id="club-info" class="back-ground-club-info">
        <div class="main-div">
            <div class="first-div">
                <div class="f-first-div">
                    <div class="ff-f-first-div">
                        <div class="club-name">
                            <p><strong>{{ club.club_name }}</strong></p>
                        </div>
                        <div class="club-category">
                            {% if club.pk == 1 %}
                            <img src="{% static "images/club_disciplines/dressage.png" %}" alt="Dressage">
                            <img src="{% static "images/club_disciplines/show jumping.png" %}" alt="Dressage">
                            <img src="{% static "images/club_disciplines/vaulting.png" %}" alt="Dressage">
                            {% else %}
                            <img src="{% static "images/club_disciplines/endurance.png" %}" alt="Dressage">
                            <img src="{% static "images/club_disciplines/eventing.png" %}" alt="Dressage">
                            {% endif %}
                        </div>
                    </div>
                    <div class="ss-f-first-div">
                        <div class="club-logo">
                            <!-- for the presentation of the site -->
                            {% if club.pk == 1 %}
                            <img src="{% static "images/basic_pictures/club_eclipse.png" %}" alt="Club Image">
                            {% else %}
                            <img src="{% static "images/basic_pictures/moon_legacy.png" %}" alt="Club Image">
                            {% endif %}
{#                            <!-- the true order <img src="{{ club.club_logo.url }}" alt="Club Image"> -->#}
                        </div>
                        <div class="club-awards">
                            <p class="club-awards-p">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#ffd700" class="bi bi-award-fill" viewBox="0 0 16 16">
                                        <path d="m8 0 1.669.864 1.858.282.842 1.68 1.337 1.32L13.4 6l.306 1.854-1.337 1.32-.842 1.68-1.858.282L8 12l-1.669-.864-1.858-.282-.842-1.68-1.337-1.32L2.6 6l-.306-1.854 1.337-1.32.842-1.68L6.331.864 8 0z"/>
                                        <path d="M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1 4 11.794z"/>
                                    </svg>
                                    <i>{{ club.award_gold }}</i>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#bfc1c2" class="bi bi-award-fill" viewBox="0 0 16 16">
                                        <path d="m8 0 1.669.864 1.858.282.842 1.68 1.337 1.32L13.4 6l.306 1.854-1.337 1.32-.842 1.68-1.858.282L8 12l-1.669-.864-1.858-.282-.842-1.68-1.337-1.32L2.6 6l-.306-1.854 1.337-1.32.842-1.68L6.331.864 8 0z"/>
                                        <path d="M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1 4 11.794z"/>
                                    </svg>
                                    <i>{{ club.award_silver }}</i>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#cdab7e" class="bi bi-award-fill" viewBox="0 0 16 16">
                                        <path d="m8 0 1.669.864 1.858.282.842 1.68 1.337 1.32L13.4 6l.306 1.854-1.337 1.32-.842 1.68-1.858.282L8 12l-1.669-.864-1.858-.282-.842-1.68-1.337-1.32L2.6 6l-.306-1.854 1.337-1.32.842-1.68L6.331.864 8 0z"/>
                                        <path d="M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1 4 11.794z"/>
                                    </svg>
                                    <i>{{ club.award_bronze }}</i>
                                </p>
                        </div>
                    </div>
                </div>
                <div class="s-first-div">
                    <div class="ff-s-first-div">
                        <div class="club-phone">
                            <i class="fa-solid fa-mobile-screen"></i>
                            <p>{{ club.club_phone_number }}</p>
                        </div>
                        <div class="club-address">
                            <i class="fa-solid fa-warehouse"></i>
                            <p>{{ club.address }}</p>
                        </div>
                        <div class="club-email">
                            <i class="fa-regular fa-paper-plane"></i>
                            <p>{{ club.email_club }}</p>
                        </div>
                    </div>
                    <div class="ss-s-first-div">
                        {% if request.user.is_staff %}
                        <div class="club-edit">
                            <a href="{% url 'edit club' club.pk %}#edit-club" >Edit Club</a>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="second-div">
                <div class="f-second-div">
                    {% if club.pk == 1 %}
                    <img src="{% static "images/clubs_ema_pic/eclipse-team.jpg" %}" alt="Pic">
                    {% else %}
                    <img src="{% static "images/clubs_ema_pic/moonlight-pic.jpg" %}" alt="Pic">
                    {% endif %}
                    <p>{{ club.description }}</p>
                </div>
            </div>
            <div class="third-div">
                <div class="f-third-div">
                    {% if club.pk == 1 %}
                    <img src="{% static "images/clubs_ema_pic/eclipse-medals.jpg" %}" alt="Pic">
                    {% else %}
                    <img src="{% static "images/clubs_ema_pic/ema_shoki.jpg" %}" alt="Pic">
                    {% endif %}
                    <p>Lorem ipsum dolor sit amet consectetur adipiscing elit,
                        urna consequat felis vehicula class ultricies mollis
                        dictumst, aenean non a in donec nulla. Phasellus ante
                        pellentesque erat cum risus consequat imperdiet aliquam,
                        integer placerat et turpis mi eros nec lobortis taciti,
                        vehicula nisl litora tellus ligula porttitor metus.
                    </p>
                </div>
            </div>
            <h4>Trainer</h4>
            <div class="club-trainer">
                {% for trainer in club.trainer_set.all %}
                <div>
                    <a href="#">{{ trainer }}</a>
                </div>
                {% endfor %}
            </div>
        </div>
     </section>
{% endblock %}

templates/web/clubs_list.html
{% extends 'bases/base.html' %}
{% load static %}

{% block co_base %}
    <section id="clubs-section" class="clubs-section">
        <div class="clubs-section-head">
            <div class="search">
                <form class="search-form" method="get" action="{% url "search club" %}">
                    {% csrf_token %}
                    <input type="search" class="search-input" name="search" placeholder="Club name...">
                    <button class="btn_search" ><i class="fa-solid fa-magnifying-glass"></i></button>
                </form>
            </div>
            <h2 class="clubs-section-h2">Find club</h2>
        </div>
        <div class="swiper mySwiper clubs-container">
            <div class="swiper-wrapper">
            {% if object_list %}
            {% for club in object_list %}
                <article id="catalogPage" class="swiper-slide club-article">
                    <div class="card-box">
                        <div class="text-center">
                            <span class="name" ><strong>{{ club.club_name }}</strong></span>
                            <p class="description">{{ club.description }}</p>
                            <div class="awards">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#ffd700" class="bi bi-award-fill" viewBox="0 0 16 16">
                                    <path d="m8 0 1.669.864 1.858.282.842 1.68 1.337 1.32L13.4 6l.306 1.854-1.337 1.32-.842 1.68-1.858.282L8 12l-1.669-.864-1.858-.282-.842-1.68-1.337-1.32L2.6 6l-.306-1.854 1.337-1.32.842-1.68L6.331.864 8 0z"/>
                                    <path d="M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1 4 11.794z"/>
                                </svg>
                                <i>{{ club.award_gold }}</i>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#bfc1c2" class="bi bi-award-fill" viewBox="0 0 16 16">
                                    <path d="m8 0 1.669.864 1.858.282.842 1.68 1.337 1.32L13.4 6l.306 1.854-1.337 1.32-.842 1.68-1.858.282L8 12l-1.669-.864-1.858-.282-.842-1.68-1.337-1.32L2.6 6l-.306-1.854 1.337-1.32.842-1.68L6.331.864 8 0z"/>
                                    <path d="M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1 4 11.794z"/>
                                </svg>
                                <i>{{ club.award_silver }}</i>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#cdab7e" class="bi bi-award-fill" viewBox="0 0 16 16">
                                    <path d="m8 0 1.669.864 1.858.282.842 1.68 1.337 1.32L13.4 6l.306 1.854-1.337 1.32-.842 1.68-1.858.282L8 12l-1.669-.864-1.858-.282-.842-1.68-1.337-1.32L2.6 6l-.306-1.854 1.337-1.32.842-1.68L6.331.864 8 0z"/>
                                    <path d="M4 11.794V16l4-1 4 1v-4.206l-2.018.306L8 13.126 6.018 12.1 4 11.794z"/>
                                </svg>
                                <i>{{ club.award_bronze }}</i>
                            </div>
                        </div>
                        <div class="btn-group">
                            <p class="rating" >Rating: {{ club.rating }}
                                {% if request.user.is_authenticated %}
                                    <a class="likes" href="{% url 'like club' club.pk %}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#EF7D00" class="bi bi-hand-thumbs-up-fill" viewBox="0 0 16 16">
                                        <path d="M6.956 1.745C7.021.81 7.908.087 8.864.325l.261.066c.463.116.874.456 1.012.965.22.816.533 2.511.062 4.51a9.84 9.84 0 0 1 .443-.051c.713-.065 1.669-.072 2.516.21.518.173.994.681 1.2 1.273.184.532.16 1.162-.234 1.733.058.119.103.242.138.363.077.27.113.567.113.856 0 .289-.036.586-.113.856-.039.135-.09.273-.16.404.169.387.107.819-.003 1.148a3.163 3.163 0 0 1-.488.901c.054.152.076.312.076.465 0 .305-.089.625-.253.912C13.1 15.522 12.437 16 11.5 16H8c-.605 0-1.07-.081-1.466-.218a4.82 4.82 0 0 1-.97-.484l-.048-.03c-.504-.307-.999-.609-2.068-.722C2.682 14.464 2 13.846 2 13V9c0-.85.685-1.432 1.357-1.615.849-.232 1.574-.787 2.132-1.41.56-.627.914-1.28 1.039-1.639.199-.575.356-1.539.428-2.59z"/>
                                        </svg>
                                    </a>
                                {% endif %}
                            </p>
                            <div class="alert-rate" style="display: none">
                                <p>You can rate only once</p>
                            </div>
                            <a href="{% url 'club info' club.pk %}#club-info"><strong>More Info</strong></a>
                        </div>
                    </div>
                </article>
                {% endfor %}
            {% else %}
                <h2>No results found!</h2>
            {% endif %}
            </div>
        <div class="swiper-pagination"></div>
        </div>
    </section>
    <script>
        document.querySelectorAll('.likes').forEach(e => e.addEventListener('mouseover', (ev) => {
            ev.currentTarget.parentNode.parentNode.querySelector('.alert-rate').style.display = 'block';
        }))
        document.querySelectorAll('.likes').forEach(e => e.addEventListener('mouseout', (ev) => {
            ev.currentTarget.parentNode.parentNode.querySelector('.alert-rate').style.display = 'none';
        }))
    </script>
    <script src="https://cdn.jsdelivr.net/npm/swiper@9/swiper-bundle.min.js"></script>
    <script>
        const swiper = new Swiper(".mySwiper", {
            effect: "coverflow",
            grabCursor: true,
            centeredSlides: true,
            slidesPerView: "auto",
            coverflowEffect: {
                rotate: 50,
                stretch: 0,
                depth: 100,
                modifier: 1,
                slideShadows: true,
            },
            pagination: {
                el: ".swiper-pagination",
            },
        });
    </script>
{% endblock %}

templates/web/create_club.html
{% extends 'bases/base.html' %}

{% block co_club_registration %}
     <div id="club-registration" class="club-reg">
        <a href="/" ><i class="fa-solid fa-xmark fa-club"></i></a>
            <form class="club-reg-form" method="post" action="{% url 'create club' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <h2 class="club-form-heading">Club Registration</h2>
                <div class="input-club">
                    {{ form.club_name }}
                    {{ form.errors.club_name }}
                    <span>Club Name</span>
                </div>
                <div class="input-club">
                    {{ form.owner }}
                    {{ form.errors.owner }}
                    <span>Owner Name</span>
                </div>
                <div class="input-club">
                    {{ form.email_club }}
                    <span>Club Email</span>
                </div>
                <div class="input-club">
                    {{ form.address }}
                    <span>Club Address</span>
                </div>
                <div class="input-club">
                    {{ form.club_phone_number }}
                    {{ form.errors.club_phone_number }}
                    <span>Club Phone Number</span>
                </div>
                <div class="input-club">
                    {{ form.description }}
                    <span>Description</span>
                </div>
                <div class="input-club">
                    {{ form.club_logo }}
                    <i class="fa-regular fa-image"></i>
                    <p class="show-logo"></p>
                    <span class="span-club-logo">Club Logo</span>
                </div>
                <button class="club-reg-btn">Registration</button>
            </form>
        </div>
    <script>
    let p_tag = document.querySelector('.show-logo');
    document.querySelector('input[type=file]').addEventListener("change", () => {
        p_tag.textContent = document.querySelector('input[type=file]').files[0].name;
    })
    </script>
{% endblock %}

templates/web/horse_breeds.html
{% extends 'bases/base.html' %}
{% load static %}

{% block co_base %}
    <section id="horse-breeds" class="horse-breeds">
        <div class="horse-heading">
            <h1 class="breed-heading">Discover your horse breed</h1>
        </div>
        <div class="breeds-wrapper">
        {% for breed in object_list %}
            <div class="breed-pic">
                <a href="{% url 'breed info' breed.pk %}#breed-info">
                    {% if breed.breed_photo %}
                    <img src="{{ breed.breed_photo.url }}" alt="East Bulgarian Horse">
                    {% else %}
                        <!-- for demo site -->
                        {% if breed.breed == 'East Bulgarian' %}
                        <img src="{% static "images/site-static-breeds-pic/East-Bulgarian-Horse.jpg" %}" alt="East Bulgarian Horse">
                        {% elif breed.breed == 'Friesian' %}
                        <img src="{% static "images/site-static-breeds-pic/friesian 2.jpg" %}" alt="Friesian Horse">
                        {% elif breed.breed == 'Thoroughbred' %}
                        <img src="{% static "images/site-static-breeds-pic/Thoroughbred-light.jpg" %}" alt="Thoroughbred Horse">
                        {% elif breed.breed == 'Arab' %}
                        <img src="{% static "images/site-static-breeds-pic/Black-Arabian-Stallion-horse-breed.jpg" %}" alt="Arab Horse">
                        {% endif %}
                    {% endif %}
                </a>
                <div class="disc-pic" >{{ breed.breed }} Horse</div>
            </div>
        {% endfor %}
        </div>
    </section>
{% endblock %}

templates/web/pay_page.html
{% extends 'bases/base.html' %}

{% block co_payment %}
    <div class="body-payment">
        <h1 class="pay-heading">Payment</h1>
        <div class="div-form-pay">
            <form class="pay-form" method="get" action="{% url 'create club' %}" enctype="multipart/form-data">
                {% csrf_token %}
                <label for="p-card" id="p-card-l">card number</label>
                <input id="p-card-i" type="text" name="text-card">
                <label for="o-name" id="o-name-l">name on card</label>
                <input id="o-name-i" type="text" name="text-name">
                <label for="ex-date" id="ex-date-l">expiry date</label>
                <input id="ex-date-i" type="text" name="text-date" disabled placeholder="mm&nbsp;&nbsp;/&nbsp;&nbsp;yy">
                <label for="cvv-card" id="cvv-l">cvv/cvc2</label>
                <input id="cvv-i" type="text" name="cvv-card" disabled>
                <div class="cards-options">
                    <i class="fa-brands fa-cc-mastercard"></i>
                    <i class="fa-brands fa-cc-visa"></i>
                </div>
                <input type="submit" value="Go To Club Registration" />
            </form>
        </div>
    </div>
{% endblock %}